version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 778404080221.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URI=778404080221.dkr.ecr.us-east-1.amazonaws.com/django-app-avto3
      - IMAGE_TAG=$(echo $VERSION.$CODEBUILD_BUILD_NUMBER)
  build:
    commands:
      - docker build -t django-app-avto3:latest .
      - echo rename image
      - docker tag django-app-avto3:latest 778404080221.dkr.ecr.us-east-1.amazonaws.com/django-app-avto3:latest
      - docker push 778404080221.dkr.ecr.us-east-1.amazonaws.com/django-app-avto3:latest
      - printf '[{"name":"django-app-avto-container","imageUri":"%s"}]' $REPO_URI:latest > avto-django-app2-imagedefinitions.json
      - docker image ls
  post_build:
    commands:
      - echo finish
artifacts:
  files:
    - avto-django-app2-imagedefinitions.json
